/**
 * lib/escrow.ts — RaiseGG multi-chain escrow client
 *
 * Unified interface over:
 *   - Solana  → Anchor program (raise_gg)
 *   - EVM     → RaiseGGEscrow.sol (ETH mainnet + BNB Chain)
 *
 * Usage (frontend):
 *   const { vaultPda, txSignature } = await createMatchSolana(...)
 *   const { txHash }                = await createMatchEvm(...)
 */

// ─── Solana ──────────────────────────────────────────────────────────────────

import {
  Connection,
  PublicKey,
} from '@solana/web3.js'
import { getAssociatedTokenAddress } from '@solana/spl-token'
import type { AnchorWallet } from '@solana/wallet-adapter-react'
import { AnchorProvider, Program, BN } from '@coral-xyz/anchor'

// ── IDL (generated by `anchor build` — placeholder types until first build) ──

function getProgramId(): PublicKey {
  const id = process.env.NEXT_PUBLIC_SOLANA_PROGRAM_ID
  if (id && id.length >= 32 && id.length <= 44 && !id.startsWith('PLACEHOLDER') && !id.startsWith('RGG')) {
    try { return new PublicKey(id) } catch (_) {}
  }
  return new PublicKey('11111111111111111111111111111111')
}

export const USDC_MINT_SOLANA = new PublicKey(
  'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v' // USDC on Solana mainnet
)

export const USDT_MINT_SOLANA = new PublicKey(
  'Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB' // USDT on Solana mainnet
)

export type StakeCurrency = 'usdc' | 'usdt'

export function getMintForCurrency(currency: StakeCurrency): PublicKey {
  return currency === 'usdt' ? USDT_MINT_SOLANA : USDC_MINT_SOLANA
}

/** Convert a UUID string ("xxxxxxxx-xxxx-...") to a 16-byte Uint8Array */
export function uuidToBytes(uuid: string): number[] {
  const hex = uuid.replace(/-/g, '')
  const arr: number[] = []
  for (let i = 0; i < 32; i += 2) arr.push(parseInt(hex.slice(i, i + 2), 16))
  return arr
}

/** Derive the match_state PDA address */
export function getMatchStatePda(matchId: string): PublicKey {
  const [pda] = PublicKey.findProgramAddressSync(
    [Buffer.from('match'), Buffer.from(uuidToBytes(matchId))],
    getProgramId()
  )
  return pda
}

/** Derive the vault PDA address */
export function getVaultPda(matchId: string): PublicKey {
  const [pda] = PublicKey.findProgramAddressSync(
    [Buffer.from('vault'), Buffer.from(uuidToBytes(matchId))],
    getProgramId()
  )
  return pda
}

/**
 * Build + send createMatch instruction on Solana.
 * Returns the vault PDA address and transaction signature.
 */
export async function solanaCreateMatch(
  connection: Connection,
  wallet: AnchorWallet,
  matchId: string,
  stakeUsdc: number,          // in full token units (e.g. 10 for $10)
  authorityPubkey: string,    // backend authority pubkey stored in NEXT_PUBLIC_TREASURY_SOL
  currency: StakeCurrency = 'usdc'
): Promise<{ vaultPda: string; txSignature: string }> {
  // Import IDL dynamically — only exists after `anchor build`
  const idl = await import('../anchor/target/idl/raise_gg.json')
  const provider = new AnchorProvider(connection, wallet, { commitment: 'confirmed' })
  const program = new Program(idl as any, provider)

  const mint         = getMintForCurrency(currency)
  const matchIdBytes = uuidToBytes(matchId)
  const stakeAmount  = new BN(stakeUsdc * 1_000_000) // 6 decimals for both USDC and USDT
  const authority    = new PublicKey(authorityPubkey)

  const playerAta   = await getAssociatedTokenAddress(mint, wallet.publicKey)
  const matchStatePda = getMatchStatePda(matchId)
  const vaultPda    = getVaultPda(matchId)

  const tx = await (program.methods as any)
    .createMatch(matchIdBytes, stakeAmount, authority)
    .accounts({
      playerA:         wallet.publicKey,
      playerAAta:      playerAta,
      matchState:      matchStatePda,
      vault:           vaultPda,
      usdcMint:        mint,
    })
    .rpc({ commitment: 'confirmed' })

  return { vaultPda: vaultPda.toString(), txSignature: tx }
}

/**
 * Build + send joinMatch instruction on Solana.
 */
export async function solanaJoinMatch(
  connection: Connection,
  wallet: AnchorWallet,
  matchId: string,
  currency: StakeCurrency = 'usdc'
): Promise<{ txSignature: string }> {
  const idl = await import('../anchor/target/idl/raise_gg.json')
  const provider = new AnchorProvider(connection, wallet, { commitment: 'confirmed' })
  const program = new Program(idl as any, provider)

  const mint = getMintForCurrency(currency)
  const matchIdBytes = uuidToBytes(matchId)
  const playerBata = await getAssociatedTokenAddress(mint, wallet.publicKey)
  const matchStatePda = getMatchStatePda(matchId)
  const vaultPda = getVaultPda(matchId)

  const tx = await (program.methods as any)
    .joinMatch(matchIdBytes)
    .accounts({
      playerB:    wallet.publicKey,
      playerBAta: playerBata,
      matchState: matchStatePda,
      vault:      vaultPda,
    })
    .rpc({ commitment: 'confirmed' })

  return { txSignature: tx }
}

/**
 * Resolve a match (called by backend authority, not frontend).
 * Used in /api/matches/resolve for Solana-chain matches.
 */
export async function solanaResolveMatch(
  connection: Connection,
  matchId: string,
  winnerPublicKey: string,
  currency: StakeCurrency = 'usdc'
): Promise<{ txSignature: string }> {
  const { Keypair } = await import('@solana/web3.js')
  const keyStr = process.env.SOLANA_AUTHORITY_PRIVATE_KEY ?? '[]'
  let authorityKeypair: InstanceType<typeof Keypair>
  if (keyStr.startsWith('[')) {
    authorityKeypair = Keypair.fromSecretKey(Uint8Array.from(JSON.parse(keyStr)))
  } else {
    const bs58 = await import('bs58')
    authorityKeypair = Keypair.fromSecretKey(bs58.default.decode(keyStr))
  }

  const idl = await import('../anchor/target/idl/raise_gg.json')

  // Build a NodeWallet-style adapter for the backend keypair
  const { Transaction: LegacyTransaction } = await import('@solana/web3.js')
  const wallet: AnchorWallet = {
    publicKey: authorityKeypair.publicKey,
    signTransaction: async (tx) => { if (tx instanceof LegacyTransaction) tx.partialSign(authorityKeypair); return tx },
    signAllTransactions: async (txs) => { txs.forEach(t => { if (t instanceof LegacyTransaction) t.partialSign(authorityKeypair) }); return txs },
  }

  const provider = new AnchorProvider(connection, wallet, { commitment: 'confirmed' })
  const program = new Program(idl as any, provider)

  const mint = getMintForCurrency(currency)
  const winner = new PublicKey(winnerPublicKey)
  const winnerAta = await getAssociatedTokenAddress(mint, winner)
  const treasury = new PublicKey(process.env.NEXT_PUBLIC_TREASURY_SOL ?? '')
  const treasuryAta = await getAssociatedTokenAddress(mint, treasury)

  const matchIdBytes = uuidToBytes(matchId)
  const matchStatePda = getMatchStatePda(matchId)
  const vaultPda = getVaultPda(matchId)

  const tx = await (program.methods as any)
    .resolveMatch(matchIdBytes, winner)
    .accounts({
      authority:   authorityKeypair.publicKey,
      winnerAta,
      treasuryAta,
      matchState:  matchStatePda,
      vault:       vaultPda,
    })
    .rpc({ commitment: 'confirmed' })

  return { txSignature: tx }
}

/**
 * Cancel a match on Solana (called by backend authority).
 * Refunds player A (open) or both players (locked).
 */
export async function solanaCancelMatch(
  connection: Connection,
  matchId: string,
  playerAPublicKey: string,
  playerBPublicKey: string | null,
  status: 'open' | 'locked',
  currency: StakeCurrency = 'usdc'
): Promise<{ txSignature: string }> {
  const { Keypair } = await import('@solana/web3.js')
  const keyStr = process.env.SOLANA_AUTHORITY_PRIVATE_KEY ?? '[]'
  let authorityKeypair: InstanceType<typeof Keypair>
  if (keyStr.startsWith('[')) {
    authorityKeypair = Keypair.fromSecretKey(Uint8Array.from(JSON.parse(keyStr)))
  } else {
    const bs58 = await import('bs58')
    authorityKeypair = Keypair.fromSecretKey(bs58.default.decode(keyStr))
  }

  const { Transaction: LegacyTransaction } = await import('@solana/web3.js')
  const wallet: AnchorWallet = {
    publicKey: authorityKeypair.publicKey,
    signTransaction: async (tx) => { if (tx instanceof LegacyTransaction) tx.partialSign(authorityKeypair); return tx },
    signAllTransactions: async (txs) => { txs.forEach(t => { if (t instanceof LegacyTransaction) t.partialSign(authorityKeypair) }); return txs },
  }

  const idl = await import('../anchor/target/idl/raise_gg.json')
  const provider = new AnchorProvider(connection, wallet, { commitment: 'confirmed' })
  const program = new Program(idl as any, provider)

  const playerA = new PublicKey(playerAPublicKey)
  const playerB = status === 'locked' && playerBPublicKey
    ? new PublicKey(playerBPublicKey)
    : playerA // pass playerA again for open matches (unused by contract)

  const mint = getMintForCurrency(currency)
  const playerAAta  = await getAssociatedTokenAddress(mint, playerA)
  const playerBAta  = await getAssociatedTokenAddress(mint, playerB)
  const matchIdBytes  = uuidToBytes(matchId)
  const matchStatePda = getMatchStatePda(matchId)
  const vaultPda      = getVaultPda(matchId)

  const tx = await (program.methods as any)
    .cancelMatch(matchIdBytes)
    .accounts({
      authority:   authorityKeypair.publicKey,
      playerAAta,
      playerBAta,
      matchState:  matchStatePda,
      vault:       vaultPda,
    })
    .rpc({ commitment: 'confirmed' })

  return { txSignature: tx }
}

// ─── EVM (ETH + BNB Chain) ───────────────────────────────────────────────────
// Uses ethers.js v6. Call from frontend with window.ethereum or WalletConnect.

/**
 * ABI — only the functions the frontend needs
 * (full ABI generated by `forge build` or `hardhat compile`)
 */
export const ESCROW_ABI = [
  'function createMatch(bytes16 matchId, address token, uint256 stakeAmount) external',
  'function joinMatch(bytes16 matchId) external',
  'function resolve(bytes16 matchId, address winner) external',
  'function cancel(bytes16 matchId) external',
  'function getMatch(bytes16 matchId) external view returns (tuple(address playerA, address playerB, address token, uint256 stakeAmount, uint8 status, uint256 expiresAt, uint256 resolveBy))',
  'function isExpiredOpen(bytes16 matchId) external view returns (bool)',
  'event MatchCreated(bytes16 indexed matchId, address indexed playerA, address token, uint256 stakeAmount)',
  'event MatchJoined(bytes16 indexed matchId, address indexed playerB)',
  'event MatchResolved(bytes16 indexed matchId, address indexed winner, uint256 payout, uint256 rake)',
  'event MatchCancelled(bytes16 indexed matchId)',
] as const

/** Contract addresses per chain ID */
export const ESCROW_ADDRESSES: Record<number, string> = {
  1:   process.env.NEXT_PUBLIC_ESCROW_ETH  ?? '',   // Ethereum mainnet
  56:  process.env.NEXT_PUBLIC_ESCROW_BNB  ?? '',   // BNB Chain
  // 11155111: '...',  // Sepolia testnet
  // 97:       '...',  // BNB testnet
}

/** USDC contract addresses per chain ID */
export const USDC_ADDRESSES: Record<number, string> = {
  1:   '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48', // ETH USDC
  56:  '0x8AC76a51cc950d9822D68b83fE1Ad97B32Cd580d', // BNB USDC
}

/** USDT contract addresses per chain ID */
export const USDT_ADDRESSES: Record<number, string> = {
  1:   '0xdAC17F958D2ee523a2206206994597C13D831ec7', // ETH USDT
  56:  '0x55d398326f99059fF775485246999027B3197955', // BNB USDT (BSC-USD)
}

export function getTokenAddress(currency: StakeCurrency, chainId: number): string {
  const map = currency === 'usdt' ? USDT_ADDRESSES : USDC_ADDRESSES
  return map[chainId] ?? ''
}

export const ERC20_APPROVE_ABI = [
  'function approve(address spender, uint256 amount) external returns (bool)',
  'function allowance(address owner, address spender) external view returns (uint256)',
] as const

/**
 * Convert UUID string to bytes16 hex string for EVM calls
 * e.g. "550e8400-e29b-41d4-a716-446655440000" → "0x550e8400e29b41d4a716446655440000"
 */
export function uuidToBytes16(uuid: string): string {
  return '0x' + uuid.replace(/-/g, '')
}

/**
 * Create a match on EVM chain.
 * Approves USDC spend then calls createMatch.
 * Returns the transaction hash.
 */
export async function evmCreateMatch(
  provider: any,  // ethers.BrowserProvider
  matchId: string,
  stakeUsdc: bigint,
  chainId: number
): Promise<{ txHash: string }> {
  const { Contract } = await import('ethers')

  const signer = await provider.getSigner()
  const escrowAddress = ESCROW_ADDRESSES[chainId]
  const usdcAddress   = USDC_ADDRESSES[chainId]

  if (!escrowAddress || !usdcAddress) throw new Error(`Unsupported chain: ${chainId}`)

  // 1. Approve escrow to spend USDC
  const usdc = new Contract(usdcAddress, ERC20_APPROVE_ABI, signer)
  const approveTx = await usdc.approve(escrowAddress, stakeUsdc)
  await approveTx.wait()

  // 2. Create match (locks stake)
  const escrow = new Contract(escrowAddress, ESCROW_ABI, signer)
  const tx = await escrow.createMatch(uuidToBytes16(matchId), usdcAddress, stakeUsdc)
  const receipt = await tx.wait()

  return { txHash: receipt.hash }
}

/**
 * Join a match on EVM chain.
 */
export async function evmJoinMatch(
  provider: any,
  matchId: string,
  stakeUsdc: bigint,
  chainId: number
): Promise<{ txHash: string }> {
  const { Contract } = await import('ethers')

  const signer = await provider.getSigner()
  const escrowAddress = ESCROW_ADDRESSES[chainId]
  const usdcAddress   = USDC_ADDRESSES[chainId]

  // Approve then join
  const usdc = new Contract(usdcAddress, ERC20_APPROVE_ABI, signer)
  const approveTx = await usdc.approve(escrowAddress, stakeUsdc)
  await approveTx.wait()

  const escrow = new Contract(escrowAddress, ESCROW_ABI, signer)
  const tx = await escrow.joinMatch(uuidToBytes16(matchId))
  const receipt = await tx.wait()

  return { txHash: receipt.hash }
}
