[features]
seeds = true
skip-lint = false

[programs.localnet]
raise_gg = "5TVDLAMTv5hGkgAmEYZsfdyPEvuUBJtkAnqy1LkyQPLK"

[programs.mainnet]
raise_gg = "5TVDLAMTv5hGkgAmEYZsfdyPEvuUBJtkAnqy1LkyQPLK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
